### ISSUE TITLE
Questions Summary Filter Selections Broken

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#35]
Filters in Question Summary is broken as seems not to be working.

**Comment by krishnandusarkar** [comment]
![image](https://cloud.githubusercontent.com/assets/3623328/17642187/3a1ba372-615a-11e6-9b63-5800a02c5acf.png)


The grid will be blank when loaded. On selection of the above filters the grid will be populated. This was working fine before the change to datatable.

Please note that either QuestionType + Category + Difficulty Level OR Exhibitor Questions can be selected.

That means, if user selects anything from QuestionType or Category or Difficulty Level dropdown, Exhibitor Questions dropdown should be resetted to --SELECT ONE-- and vice versa.

**Comment by debasishbanerjee** [comment]
Done

**Comment by krishnandusarkar** [comment]
Partially working. Below mentioned feature is still broken and thus filtered search functionality is broken too..

Please note that either QuestionType + Category + Difficulty Level OR Exhibitor Questions can be selected.

That means, if user selects anything from QuestionType or Category or Difficulty Level dropdown, Exhibitor Questions dropdown should be resetted to --SELECT ONE-- and vice versa.

**Comment by krishnandusarkar** [comment]
Sorry, the above statement is wrong. Leave it as it is as of now. Closing the issue
