### ISSUE TITLE
Card Buttons Not Required

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#36]
Below shown buttons are not required in any of the pages. Please remove it from all pages.

![image](https://cloud.githubusercontent.com/assets/3623328/17642178/04393c06-615a-11e6-8dba-1df2232f40f2.png)

**Comment by debasishbanerjee** [comment]
Done

**Comment by snowbreeze** [comment]
edit/update pages still miss this

**Comment by krishnandusarkar** [comment]
It's still appearing on below pages.

update_category.php

update_difficulty.php

update_category_sponsors.php

Update Questions is broken. Testing blocked.

**Comment by debasishbanerjee** [comment]
Done

**Comment by krishnandusarkar** [comment]
Working Fine.
